const PEOPLE = [
  {
    name: "Ashish Kundu",
    title: "CISO, Cisco",
    company: "Cisco",
    stack: { aws: false, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Security-first data infrastructure leader; angle on zero-trust data access resonates with Bedrock's governance story.",
    background: [
      "CISO at Cisco; previously Distinguished Engineer at Palo Alto Networks",
      "Deep expertise in cloud security, data governance, and zero-trust architecture",
      "Published researcher in applied cryptography and distributed systems security",
    ],
    connections: [
      { who: "Mutual: Rahul Agarwal (Snowflake)", how: "Co-panelists at RSA 2024" },
    ],
  },
  {
    name: "Heather Ceylan",
    title: "VP Data Engineering, Salesforce",
    company: "Salesforce",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: true, mit: false, conn: true,
    relNote: "Met at Snowflake Summit 2024; expressed interest in Bedrock's lineage capabilities.",
    ai: "Running a major data modernization initiative; actively evaluating metadata and lineage tooling for 2025 budget.",
    background: [
      "VP Data Engineering at Salesforce; leads a 120-person data org",
      "Previously Director of Data Platform at LinkedIn",
      "Obsessed with data quality and operational metadata at scale",
    ],
    connections: [
      { who: "Mutual: James Park (Databricks)", how: "Former colleagues at LinkedIn" },
      { who: "Mutual: Sarah Chen (dbt Labs)", how: "Advisor relationship" },
    ],
  },
  {
    name: "Leon Bian",
    title: "Head of Data Platform, Airbnb",
    company: "Airbnb",
    stack: { aws: true, snowflake: false, databricks: true, gcp: false },
    rel: false, mit: true, conn: true,
    ai: "Built Airbnb's internal data discovery tool; deeply understands the gap between cataloging and actionable lineage.",
    background: [
      "Head of Data Platform at Airbnb; founded and scaled their data mesh initiative",
      "MIT EECS '12; active in MIT alumni data engineering community",
      "Early contributor to Apache Iceberg",
    ],
    connections: [
      { who: "Mutual: Kevin Ma (Databricks)", how: "MIT classmates, stay in close touch" },
      { who: "Mutual: Priya Patel (Airbnb)", how: "Same org" },
    ],
  },
  {
    name: "Marzi West",
    title: "CDO, Workday",
    company: "Workday",
    stack: { aws: false, snowflake: true, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Navigating the intersection of HR data sensitivity and enterprise analytics; strong champion of privacy-preserving data sharing.",
    background: [
      "CDO at Workday; oversees data strategy for 60M+ employee records",
      "Former SVP Analytics at ADP",
      "Board member, Data & Trust Alliance",
    ],
    connections: [
      { who: "Mutual: Daniel Torres (Workday)", how: "Direct report" },
      { who: "Mutual: Lisa Wang (Snowflake)", how: "Partner ecosystem" },
    ],
  },
  {
    name: "Murali Swaminathan",
    title: "SVP Engineering, Databricks",
    company: "Databricks",
    stack: { aws: true, snowflake: false, databricks: true, gcp: true },
    rel: true, mit: false, conn: true,
    relNote: "Existing partnership conversation with Bedrock's BD team; warm intro from CEO.",
    ai: "Key influencer in the Databricks Unity Catalog ecosystem; Bedrock integration story is directly relevant to his team's roadmap.",
    background: [
      "SVP Engineering at Databricks; owns Unity Catalog, Delta Lake runtime",
      "Previously VP Engineering at Palantir",
      "Deep background in distributed query engines and catalog federation",
    ],
    connections: [
      { who: "Mutual: Ankit Shah (Bedrock)", how: "Direct intro from Ankit" },
      { who: "Mutual: Reza Zadeh (Databricks co-founder)", how: "Long-time collaborator" },
    ],
  },
  {
    name: "Suhel Khan",
    title: "Director Data Architecture, Stripe",
    company: "Stripe",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Driving Stripe's transition to an event-driven data architecture; active evaluator of data observability and lineage tools.",
    background: [
      "Director Data Architecture at Stripe; designed Stripe's real-time data pipeline for payment analytics",
      "Former Senior Data Engineer at Square",
      "Speaker at Kafka Summit and dbt Coalesce",
    ],
    connections: [
      { who: "Mutual: Michael Kim (Stripe)", how: "Same team" },
      { who: "Mutual: Jenny Wu (dbt Labs)", how: "Conference circuit" },
    ],
  },
  {
    name: "Priya Nair",
    title: "VP Analytics Engineering, Uber",
    company: "Uber",
    stack: { aws: false, snowflake: true, databricks: true, gcp: false },
    rel: false, mit: true, conn: true,
    ai: "MIT alum with a focus on large-scale analytics infrastructure; potential Bedrock design partner for real-time lineage.",
    background: [
      "VP Analytics Engineering at Uber; runs the Querybuilder and Databook platform",
      "MIT Sloan MBA '14",
      "Mentor in the MIT Women in Tech network",
    ],
    connections: [
      { who: "Mutual: Leon Bian (Airbnb)", how: "MIT alumni network" },
    ],
  },
  {
    name: "David Chen",
    title: "CTO, Monte Carlo",
    company: "Monte Carlo",
    stack: { aws: true, snowflake: true, databricks: true, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Built the category-defining data observability product; understands the market dynamics Bedrock is operating in.",
    background: [
      "CTO & Co-founder at Monte Carlo",
      "Previously Staff Engineer at Salesforce and Barclays",
      "Frequent writer on data reliability engineering",
    ],
    connections: [
      { who: "Mutual: Heather Ceylan (Salesforce)", how: "Former colleague" },
      { who: "Mutual: Sarah Chen (dbt Labs)", how: "Ecosystem partners" },
    ],
  },
  {
    name: "Rasha Amin",
    title: "Principal Data Engineer, Meta",
    company: "Meta",
    stack: { aws: false, snowflake: false, databricks: true, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Works on Meta's internal data catalog (Nemo); knows firsthand the limits of build-vs-buy at hyperscaler scale.",
    background: [
      "Principal Data Engineer at Meta; core contributor to Nemo data catalog",
      "Previously at Cloudera and Hortonworks",
      "Committer on Apache Atlas",
    ],
    connections: [
      { who: "Mutual: Murali Swaminathan (Databricks)", how: "Open source collaboration" },
    ],
  },
  {
    name: "James Thornton",
    title: "Head of Data, Robinhood",
    company: "Robinhood",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Scaling data infrastructure under tight regulatory scrutiny; compliance-driven lineage is a primary budget priority.",
    background: [
      "Head of Data at Robinhood; built the data platform from seed stage through IPO",
      "Previously at Fidelity and Two Sigma",
      "Fintech data governance expert",
    ],
    connections: [
      { who: "Mutual: Suhel Khan (Stripe)", how: "FinTech data leaders roundtable" },
    ],
  },
  {
    name: "Angela Park",
    title: "SVP Data Strategy, Adobe",
    company: "Adobe",
    stack: { aws: true, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Led Adobe's Experience Platform data unification; multi-cloud data fabric is a live initiative she owns.",
    background: [
      "SVP Data Strategy at Adobe; architect of AEP's real-time CDP data layer",
      "Previously VP Product at Informatica",
      "Frequent keynote speaker at Strata and Data+AI Summit",
    ],
    connections: [
      { who: "Mutual: Lisa Wang (Snowflake)", how: "Partner ecosystem meetings" },
    ],
  },
  {
    name: "Kevin Okafor",
    title: "Director ML Infrastructure, LinkedIn",
    company: "LinkedIn",
    stack: { aws: false, snowflake: false, databricks: true, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Building the feature store and training data lineage layer for LinkedIn's AI products; Bedrock's provenance story maps directly.",
    background: [
      "Director ML Infrastructure at LinkedIn; owns feature platforms and ML data pipelines",
      "Previously at Google Brain and DeepMind",
      "PhD Computer Science, Stanford",
    ],
    connections: [
      { who: "Mutual: Heather Ceylan (Salesforce)", how: "Former LinkedIn colleague" },
    ],
  },
  {
    name: "Tara Mehta",
    title: "CDO, Snowflake",
    company: "Snowflake",
    stack: { aws: false, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Insider view on Snowflake's data governance roadmap; Bedrock's complementary position to native Snowflake features is the key angle.",
    background: [
      "CDO at Snowflake; joined from Tableau post-acquisition",
      "Oversees Horizon data governance suite strategy",
      "Board advisor at Alation",
    ],
    connections: [
      { who: "Mutual: Marzi West (Workday)", how: "Partner ecosystem" },
      { who: "Mutual: David Chen (Monte Carlo)", how: "Ecosystem partners" },
    ],
  },
  {
    name: "Brian Nakamura",
    title: "VP Platform Engineering, DoorDash",
    company: "DoorDash",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Scaling data infrastructure for a marketplace with complex multi-sided lineage needs; actively exploring metadata solutions.",
    background: [
      "VP Platform Engineering at DoorDash; built their data warehouse from ground up",
      "Previously Staff Engineer at Amazon",
      "AWS Community Hero",
    ],
    connections: [
      { who: "Mutual: Suhel Khan (Stripe)", how: "AWS ecosystem events" },
    ],
  },
  {
    name: "Claudia Rivera",
    title: "Head of Data Engineering, Lyft",
    company: "Lyft",
    stack: { aws: true, snowflake: false, databricks: true, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "Deep experience with open table formats (Hudi, Iceberg); evaluating solutions at the storage-metadata layer.",
    background: [
      "Head of Data Engineering at Lyft; led their migration from Hive to Iceberg",
      "Contributor to Apache Hudi",
      "Former data engineering lead at Pinterest",
    ],
    connections: [],
  },
  {
    name: "Samuel Wright",
    title: "Chief Data Officer, Zendesk",
    company: "Zendesk",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "New CDO role (6 months); building greenfield data strategy — ideal timing for Bedrock consideration from the start.",
    background: [
      "CDO at Zendesk; joined 6 months ago to build out enterprise data strategy",
      "Previously VP Data at ServiceNow",
      "Focus on SaaS operational analytics and customer data platforms",
    ],
    connections: [],
  },
];
