const PEOPLE = [
  {
    name: "Leon Bian",
    title: "VP & Head of Product, AI & Data Security (Databolt)",
    company: "Capital One",
    pronoun: "he",
    employees: "77,100",
    revenue: "$58.7B",
    li: "https://www.linkedin.com/in/lbian/",
    stack: { aws: true, snowflake: true, databricks: true, gcp: true },
    rel: false, mit: true, conn: true,
    ai: "Built Databolt from inside Capital One — he knows every gap in the DSPM landscape firsthand. Peer conversation, not a pitch.",
    whoTheyAre: [
      "Builder mindset. Launched and commercialized Databolt as a B2B enterprise data security platform in 2025, building and leading a 20+ person product and product marketing organization.",
      "Career: Intuit (Head of Product, Data Security) → LG Electronics → Motorola → EMC → Capital One (VP, AI & Data Security, Sep 2024–present).",
      "Vice Chair, MIT Sloan Alumni Board (Jul 2025); Steering Committee Member, MIT Sloan PM Community of Practice; MIT Educational Counselor; Venture Scout, Alumni Ventures.",
      "Education: MIT Sloan School of Management (MBA) · BS/MS Computer Science.",
    ],
    aiInitiatives: "Capital One has made governed, AI-ready data a strategic priority at the highest levels. CDO Amy Lenander has publicly stated that a strong data foundation — well-managed and governable — is the best way to ensure AI success. The bank manages several hundred petabytes of data approaching exabyte scale, with governance and discoverability treated as foundational to AI returns. Capital One has implemented granular Snowflake data sharing controls providing visibility into what data flows in and out of the company at the most granular level.\n\nOn the product side, Databolt expanded significantly at RSAC 2026: new automated workflows protect PII in unstructured formats including PDFs, emails, transcripts, and office documents; tokenization preserves semantic structure for LLM use; a 100% self-hosted deployment option was introduced for regulated businesses; and enhanced access controls deliver granular separation of responsibilities at scale.",
    worldRightNow: "$58.7B revenue. 14,000+ engineers. One of the most AI-forward financial institutions globally. Capital One 2019 AWS S3 breach — 106M records exposed — directly shaped Databolt's origins.",
    painPoints: [
      "Built Databolt because no market solution met his needs — he knows every gap in the DSPM landscape.",
      "Governing unstructured data for AI workloads at petabyte scale across S3, Snowflake, and Databricks.",
      "Bridging the gap between tokenization (Databolt's approach) and broader data intelligence — where Bedrock's classification layer sits.",
      "SEC cyber disclosure means every data visibility gap is a board-level liability.",
    ],
  },
  {
    name: "Ashish Kundu",
    title: "Head of Cybersecurity Research · IEEE Fellow",
    company: "Cisco Research",
    pronoun: "he",
    employees: "86,000",
    revenue: "$59.1B",
    li: "https://www.linkedin.com/in/ashishkundu/",
    stack: { aws: true, snowflake: true, databricks: true, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "Academic-practitioner with 5,700+ Google Scholar citations. Responds to technical depth and research rigor — not marketing language.",
    whoTheyAre: [
      "Academic-practitioner hybrid with 5,700+ Google Scholar citations. Responds to deep technical conversation and research rigor — not interested in marketing language.",
      "Career: IBM T.J. Watson Research Center (8 yrs — Research Staff Member, Master Inventor, Security & Compliance Research Lead for Watson Health Cloud HIPAA) → Head of Cybersecurity, Nuro → CTO & Co-Founder, Ciphense → Cisco Research (Head of Cybersecurity Research, May 2021–present).",
      "President of IIT Startups. Education: PhD Candidate, Computer Science, Purdue University · BS NIT Rourkela, India.",
    ],
    aiInitiatives: "Cisco has made AI governance and data security a central strategic theme in 2026. In January, Cisco published its 2026 Data and Privacy Benchmark Study (5,200+ professionals across 12 markets): 90% of organizations expanded privacy programs due to AI; 38% now spend at least $5M annually on privacy (up from 14% in 2024); 65% struggle to efficiently access high-quality data for AI; and 83% advocate for harmonized international data governance standards.\n\nAt Cisco Live EMEA (February 2026), Cisco announced a sweeping evolution of its security portfolio for the agentic era — combining agent protection, interaction governance, and resilient connectivity. At RSAC 2026, Cisco extended Zero Trust Access to AI agents, introduced Duo IAM capabilities integrating with MCP policy enforcement, and launched Splunk AI to automate security response at machine speed. Cisco's State of AI Security 2026 report documented the proliferation of agentic AI threats and prompt injection attacks.",
    worldRightNow: "Cisco investing heavily in AI agent security via Outshift. $59.1B revenue. AppDynamics is part of the Cisco family. Ashish's IBM background includes direct HIPAA compliance and cloud security work for Watson Health — deep expertise in governing sensitive data at scale.",
    painPoints: [
      "Securing AI agent access to sensitive data at enterprise scale — his primary published research focus.",
      "Data governance across cloud platforms at 86,000-person organizational scale.",
      "Quantum-resistant data protection for long-lived sensitive data.",
      "How DSPM integrates with identity and access control — the data classification layer that makes access governance actionable.",
    ],
  },
  {
    name: "Heather Ceylan",
    title: "SVP & Chief Information Security Officer",
    company: "Box",
    pronoun: "she",
    employees: "2,912",
    revenue: "$1.18B",
    li: "https://www.linkedin.com/in/heatherceylan/",
    stack: { aws: true, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Shadow AI accessing Box content is her stated #1 concern for 2026. Launched Box Shield Pro with AI Classification Agent — content governance is her daily reality.",
    whoTheyAre: [
      "AI-forward optimist. Publicly calls AI a force multiplier for security teams. Practiced conference speaker — takes the intellectual side of security seriously.",
      "Career: Collective Health (VP Security, Privacy and Compliance) → Zoom (Head of Security GRC, Jan 2021–Feb 2023) → Box (CISO, May 2024–present).",
      "Board member CISO Ascent. Editorial board, Cyber Security peer-reviewed journal.",
      "Education: BS Management Information Systems, Butler University. Certifications: CIPM (IAPP), CISM (ISACA).",
    ],
    aiInitiatives: "Box has made AI-driven content governance the center of its 2025–2026 security strategy. At BoxWorks 2025, Box launched Shield Pro with three AI-powered agents: the AI Classification Agent (automatically classifies sensitive content at scale, making governance policies travel with the content from creation); the AI Threat Analysis Agent (translates threat data into plain-language summaries embedded in Shield alerts); and Ransomware Activity Detection. Shield Pro enforces security at the content layer — policies embedded in the content itself, not just the surrounding environment.\n\nIn February 2026, Shield Pro was confirmed generally available. Box Automate (agentic workflow engine) and Box Agent launched in parallel, enabling autonomous AI actions on enterprise content. Box's AI Principles framework governs how Box AI handles customer data: transparency, permission-based access, and strict separation from AI training — explicitly aligned to the NIST AI Risk Management Framework. CEO Aaron Levie: AI agents will become the largest user of software and data in the enterprise.",
    worldRightNow: "Gartner Magic Quadrant Leader for Document Management 2026. Box serves regulated enterprises in financial services, healthcare, and legal. $1.18B revenue, net retention 105%. Heather's publicly stated concern for 2026: shadow AI outside established controls creates dangerous blind spots — sharpened by the Colorado AI Act (enforceable June 30, 2026) and the EU AI Act's high-risk obligations (August 2, 2026).",
    painPoints: [
      "Shadow AI accessing Box content outside established governance — her stated number one concern for 2026.",
      "AI agents acting on enterprise content at scale as Box Automate rolls out.",
      "Enterprise customers in regulated industries demanding proof of AI data governance.",
      "Unstructured content classification at petabyte scale across thousands of enterprise customers.",
    ],
  },
  {
    name: "Soumen Bhattacharya",
    title: "Director",
    company: "Capital One",
    pronoun: "he",
    employees: "77,100",
    revenue: "$58.7B",
    li: "https://www.linkedin.com/in/soumen-bhattacharya/",
    stack: { aws: true, snowflake: false, databricks: false, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "IAM + Data Protection + GenAI Security are his three top-listed skills — exactly where Bedrock's classification layer sits.",
    whoTheyAre: [
      "Cybersecurity & Application Security Leader focused on enterprise security strategy, application security, and cryptographic solutions. Top-listed skills: IAM, Data Protection, GenAI Security, AWS.",
      "Career: Visa → eBay → Cisco → Delta Dental → Capital One → JP Morgan Chase → Capital One (Director, present per LinkedIn). Previously at Capital One — now returned.",
      "Education: Indian Institute of Technology BHU (IIT-BHU).",
      "⚠ LinkedIn confirms Soumen is currently Director at Capital One. He may know Leon Bian directly — verify at dinner.",
    ],
    aiInitiatives: "Capital One is at the forefront of governed AI deployment. CDO Amy Lenander has made well-managed, governable data the foundation for all AI initiatives. Databolt — which Soumen is adjacent to given his return to Capital One — represents the bank's flagship data security and governance platform, expanded at RSAC 2026 to protect unstructured data for AI workloads. The bank manages several hundred petabytes under strict governance, with the JADE-equivalent data platform providing lineage, access controls, and quality SLAs. Soumen's explicit skill focus on IAM and Data Protection, combined with GenAI Security as a top-listed competency, makes him highly aligned with Bedrock's platform conversation.",
    worldRightNow: "Capital One $58.7B revenue. 14,000+ engineers. One of the most AI-forward financial institutions globally.",
    painPoints: [
      "IAM and data protection at the intersection of AI adoption — his stated expertise.",
      "GenAI Security — explicitly listed as a top skill, signals active engagement with this problem space.",
      "Data governance for AI workloads at petabyte scale across AWS, Snowflake, and Databricks.",
      "SEC cyber disclosure obligations for all data visibility gaps.",
    ],
  },
  {
    name: "Sridhar Kotamraju",
    title: "Head of Identity & Security, Commercial & Investment Banking",
    company: "J.P. Morgan",
    pronoun: "he",
    employees: null,
    revenue: "$4.6T assets",
    li: "https://www.linkedin.com/in/sridharkotamraju/",
    stack: { aws: true, snowflake: true, databricks: true, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "Sits at the rare intersection of identity governance and data governance — DSPM is directly actionable from his seat. Relationship building context, not active pipeline.",
    whoTheyAre: [
      "Deep domain expert in digital identity, authentication, and fraud. His remit at JPM explicitly covers Digital Identity & Security, Authentication & Authorization, and Fraud.",
      "Career: Head of Identity & Security C&IB, J.P. Morgan (May 2023–present) → Global Head of Fraud, Goldman Sachs → SVP Head of Product & Engineering – Fraud, Digital Identity, Authentication, PNC → Head of Fraud Corp and Institutional Banking, Wells Fargo.",
      "Entire career in financial services identity, fraud, and authentication.",
      "Note: Not on CRM target list — relationship building rather than active pipeline.",
    ],
    aiInitiatives: "Sridhar sits at the intersection of identity governance and data governance — a rare combination that makes DSPM directly actionable from his seat. JPMorgan's Firmwide CDO function aligns data platforms with model risk management, legal, and security; Sridhar's identity layer is the enforcement point for that governance. The bank's JADE data mesh and OmniAI platform require identity controls that govern not only human employees but AI agents and automated workflows.\n\nAs of June 2026, JPM is on the verge of deploying long-running autonomous agents capable of managing C&IB workflows for one to two hours without human intervention — exactly the scenario that demands identity-aware data classification. Chief Analytics Officer Derek Waldron has confirmed that security and governance checks are the gating requirement before those agents ship. JPM's governance framework applies the tightest controls at the C&IB layer: OCC, SEC cyber disclosure, DORA, and SOX all apply simultaneously.",
    worldRightNow: "JPMorganChase $4.6T assets. C&IB handles institutional clients with the highest-value data in the bank.",
    painPoints: [
      "Identity and access governance for AI agents accessing C&IB data — long-running agents make this urgent now.",
      "Data classification at the intersection of identity and data security — his remit covers both layers.",
      "OCC, SEC cyber disclosure, DORA, SOX — all apply simultaneously to the data his team protects.",
      "Cross-platform governance as JPM scales to 1,000 AI use cases.",
    ],
  },
  {
    name: "Suhel Khan",
    title: "Head of Cyber Security · Senior Director",
    company: "Chargebee",
    pronoun: "he",
    employees: "1,304",
    revenue: "$273.9M",
    li: "https://www.linkedin.com/in/suhel-khan-3b75226/",
    stack: { aws: true, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "Processes billing and payment data for 6,500+ SaaS and AI-native companies. Deep financial services background — evaluates vendors on depth and evidence.",
    whoTheyAre: [
      "Built digital security for Chargebee's fintech platform, focused on 'building to last' with key security infrastructure.",
      "Career: Fidelity Investments (Director Information Security, ~5 yrs 11 mos) → InMobi (CISO) → Marcus by Goldman Sachs (Head of Tech Risk, VP) → Chargebee (Head Cyber Security, Senior Director, Jul 2022–present).",
      "Prior to Chargebee: deep financial services and fintech security background.",
    ],
    aiInitiatives: "Chargebee is positioning as billing infrastructure for the AI era — processing 100M+ usage events per month for 6,500+ SaaS and AI-native companies. The company acquired Inai (AI-powered payments intelligence) in September 2025. As its customers are themselves AI companies, the billing and usage data Chargebee processes is increasingly complex and sensitive.\n\nChargebee maintains ISO 27001:2022 certification, PCI-DSS Level 1 compliance, and SOC attestation. An updated Data Processing Addendum was issued February 2026, reflecting evolving CCPA and global privacy requirements. As Chargebee moves upmarket into enterprise, customers are demanding documented AI governance and sensitive data handling evidence.",
    worldRightNow: "$273.9M revenue, 1,304 employees. Gartner Magic Quadrant Leader. Moving upmarket to enterprise.",
    painPoints: [
      "Processes billing and payment data for 6,500+ companies — sensitive financial data at scale where classification is non-negotiable.",
      "Serving AI-native companies means billing data governance complexity multiplies as those customers' AI usage scales.",
      "Enterprise upmarket motion means governance evidence is now a procurement requirement, not a nice-to-have.",
      "Background in financial services security (Fidelity, Goldman) — evaluates vendors on depth and evidence.",
    ],
  },
  {
    name: "Gaurav Sabharwal",
    title: "Head of Enterprise Systems, AI Tools and Security",
    company: "New Relic",
    pronoun: "he",
    employees: null,
    revenue: "$926M",
    li: "https://www.linkedin.com/in/gauravsabharwal/",
    stack: { aws: true, snowflake: true, databricks: false, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "His title combines AI Tools and Security — he is simultaneously buying and governing AI tooling at New Relic, and publicly posting on prompt injection risks.",
    whoTheyAre: [
      "Executive responsible for security, integration platform, AI developer tools, and business systems. Actively posting on LinkedIn about AI observability, prompt injection risks, and AI agent security.",
      "Career: Pitney Bowes (9 yrs 6 mos — Head of Global Data, Technology and Tools; Executive Global Solution Success) → IBM (5 yrs 2 mos — Head of Enterprise Applications) → Genpact Headstrong Capital Markets (Practice Head Enterprise Applications, 9 yrs) → New Relic (Dec 2024–present).",
      "Deep enterprise data integration background across large multinationals.",
    ],
    aiInitiatives: "New Relic has moved aggressively on AI governance infrastructure in 2026. In February, New Relic launched its enterprise-grade Agentic Platform — a no-code solution for building and governing AI agents with MCP support, fine-grained RBAC, and audit logging as foundational governance controls. In March, New Relic launched New Relic Control, a centralized governance layer for observability with Federated APM Management and an OTTL-powered Pipeline Control Gateway.\n\nNew Relic signed the EU AI Pact in December 2025 and is opening a Tokyo data center (July 2026) for customers with data sovereignty requirements. On June 8, New Relic announced AI Coding Observability (launching June 23) — a vendor-neutral governance layer normalizing telemetry across AI coding assistants (Claude Code, Cursor, GitHub Copilot, Windsurf, Amazon Q) with a local-only/zero-outbound mode guaranteeing data sovereignty.",
    worldRightNow: "$926M revenue. Petabyte-scale telemetry platform. Recently taken private. Gaurav's current title explicitly combines AI Tools and Security — he is both buying and governing AI tooling at New Relic, making him directly relevant to Bedrock's platform.",
    painPoints: [
      "Petabyte-scale telemetry data may contain customer application PII — classification at this scale is unresolved.",
      "AI agents diagnosing incidents access telemetry spanning hundreds of customer environments with no classification layer.",
      "His title combines AI Tools and Security — he sees the governance gap between AI adoption and data control firsthand.",
      "Prompt injection in AI agents — publicly posting about this risk.",
    ],
  },
  {
    name: "Murali Swaminathan",
    title: "Chief Technology Officer",
    company: "Freshworks",
    pronoun: "he",
    employees: null,
    revenue: "$871M",
    li: "https://www.linkedin.com/in/muraliswaminathan/",
    stack: { aws: true, snowflake: false, databricks: true, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "Publicly committed to data sovereignty: 'we make sure data stays in the zone.' Founding Member, a16z speedrun — actively evaluating early-stage AI security startups as a design partner.",
    whoTheyAre: [
      "Responsible for Freshworks' technology roadmap and strategy, leading global engineering, cloud, and architecture. Forbes Technology Council Official Member (Mar 2026).",
      "Founding Member, a16z speedrun SR Insider community (Feb 2026 — invite-only executive community connecting AI startups with enterprise early adopters). Operating Advisor, Raido Capital Partners (fintech/digital commerce).",
      "Career: ServiceNow (8 yrs — VP ITSM and SPM Engineering) → Freshworks (CTO, Sep 2024–present).",
      "Education: MS Software Engineering Management, Carnegie Mellon University · BS Electronics, Annamalai University · UC Berkeley Executive Education alum.",
    ],
    aiInitiatives: "Murali has made AI governance and data sovereignty a public priority. In a May 2026 interview at Freshworks Refresh, he described the company's layered governance architecture: LLM guardrails defining permitted behavior; agent-level boundaries keeping automated systems focused; data anonymization policies; and data sovereignty controls ensuring data stays within designated geographic zones. His direct quote: \"We focus on data sovereignty — we make sure that the data stays in the zone and doesn't go outside.\"\n\nIn May 2026, Freshworks launched Freddy AI Agent Studio and MCP Gateway, introducing RBAC, auditability, deployment guardrails, and analytics for continuous governance improvement. The Freddy AI Trust framework includes content safety filters, prompt injection protection, regional data residency, and customer-isolated model training. Freshworks handles PII across 68,000+ customers.",
    worldRightNow: "$871M revenue, publicly traded. Aggressively moving upmarket from SMB to enterprise. His a16z speedrun membership means he is actively evaluating early-stage AI security startups as a design partner.",
    painPoints: [
      "Enterprise data governance requirements — including classification evidence for regulated PII — are contractually mandatory as Freshworks moves upmarket.",
      "Handles customer PII across 68,000 companies — classification at that scale is a foundational, unsolved problem.",
      "Databricks in the stack means AI training data governance is a live concern.",
      "As CTO, must prove AI is safe and governed to enterprise buyers — data security is a sales enablement issue.",
    ],
  },
  {
    name: "Anirban De",
    title: "Head of GRC Assurance & Automation",
    company: "Uber",
    pronoun: "he",
    employees: "35,000",
    revenue: "$53.7B",
    li: "https://www.linkedin.com/in/anirban-d-10aa2836/",
    stack: { aws: true, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "Post-Lapsus breach, continuous data governance visibility is a board mandate at Uber. Frame around compliance evidence — not threat hunting language.",
    whoTheyAre: [
      "Compliance and governance practitioner. Built his early career doing large enterprise IT consulting before moving into GRC and compliance automation.",
      "Career: Deloitte (4 yrs 1 mo — Consultant India then Senior Consultant Greater Philadelphia) → Uber (Head of GRC Assurance & Automation, current).",
      "Education: BE Electronics and Communication, Netaji Subhas Institute of Technology (CGPA 3.93).",
    ],
    aiInitiatives: "Uber has elevated data governance and AI governance to formal board-level oversight in 2026. Per Uber's 2026 Proxy Statement: the Full Board receives regular updates on AI governance covering strategy, risk management, and regulatory engagement; the Chief Privacy Officer reports to the Board at least annually on enterprise privacy and AI governance risk; the CISO reports quarterly to the Audit Committee. Uber appointed Nikesh Arora to the Board specifically for his cybersecurity and AI expertise.\n\nUber has also expanded its public AI governance disclosures — publishing its first European Algorithmic Transparency Report, launching a Responsible AI webpage, and releasing the ORCAA algorithmic audit report. Uber's 2026 10-Q explicitly flags AI and ML as a material risk area. Simultaneously, Uber is processing 25% YoY gross bookings growth and integrating M&A acquisitions (Getir, Trendyol GO) — all of which generate new data sprawl that Anirban's GRC function must track.",
    worldRightNow: "$53.7B revenue. Publicly traded. AWS+GCP stack. Active M&A creating new data consolidation complexity. Post-Lapsus breach (2022), board-level data visibility requirements are a standing mandate.",
    painPoints: [
      "Post-Lapsus breach, continuous data governance visibility is a board mandate — audit evidence must be always-on.",
      "M&A consolidation (Getir, Trendyol) creates data sprawl across new geographies that GRC frameworks struggle to track.",
      "Frame around continuous compliance evidence — not threat hunting language.",
      "AWS+GCP only; unstructured data governance is the entry point.",
    ],
  },
  {
    name: "Umashankar Meda",
    title: "Director, BTP Risk Management and Compliance",
    company: "SAP",
    pronoun: "he",
    employees: "107,000",
    revenue: "$34.2B",
    li: "https://www.linkedin.com/in/umameda/",
    stack: { aws: true, snowflake: true, databricks: true, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "BTP is the integration layer connecting SAP to AWS, Snowflake, Databricks, and GCP — he must govern data flows across all of them simultaneously.",
    whoTheyAre: [
      "BTP Information Security Global Compliance Lead — ensuring SAP's Business Technology Platform adheres to global compliance and regulatory standards.",
      "Career: SAP SuccessFactors (Sr Manager Security and Compliance PMO) → Cisco (5 yrs 8 mos — Sr IT Program Manager Customer Success) → SAP (Director BTP Risk Management and Compliance, Oct 2025–present).",
      "Certifications: MBA, CISA, CISM.",
    ],
    aiInitiatives: "SAP made its most transformative AI and governance announcement in years at Sapphire 2026 (May). SAP unveiled the 'Autonomous Enterprise' vision, anchored by a unified SAP Business AI Platform combining BTP, Business Data Cloud, and Business AI, structured around three layers: context, build, and governance. SAP CEO Christian Klein: \"We anchor AI agents in the business processes, data and governance so they can deliver accurate, compliant and secure outcomes.\"\n\nSAP launched Joule Studio for enterprise-scale agentic development with enterprise-grade security, approval flows, compliance processes, identity management, and full auditability. The governance layer is anchored by the new SAP AI Agent Hub — a single command center to discover, manage, and govern all AI agents, SAP and non-SAP alike. In Q1 2026, SAP released AI hardening evaluation features improving compliance with security guidelines by 27% and reducing remediation effort by 32%. Autonomous HCM Joule Assistants (Core HR, Payroll, Time, Compensation) reach general availability in June 2026 — putting agentic access to sensitive HR data into production right now.",
    worldRightNow: "$34.2B revenue. Full modern stack. SAP systems contain some of the most sensitive enterprise data: financials, HR, and supply chain.",
    painPoints: [
      "BTP is the integration layer connecting SAP to AWS, Snowflake, Databricks, and GCP — he must govern data flows across all of it.",
      "SAP Joule agents accessing HR, financial, and supply chain data — compliance must track and document the exposure.",
      "His role requires continuous audit evidence — Bedrock's classification output feeds directly into that workflow.",
      "Governance at 107,000-employee enterprise scale is an audit obligation, not optional.",
    ],
  },
  {
    name: "Mark Roeder",
    title: "Director, Defensive Cyber Operations",
    company: "Okta",
    pronoun: "he",
    employees: null,
    revenue: "$2.92B",
    li: "https://www.linkedin.com/in/mark-roeder-5702591/",
    stack: { aws: true, snowflake: true, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "Okta's identity graph contains the entitlement data that makes DSPM actionable — Bedrock tells you what the data is, Okta controls who touches it.",
    whoTheyAre: [
      "Securing Okta globally — people, processes, detection and response. Building a scalable security-minded DCO team. Actively posting on LinkedIn about AI SOC and adversarial exposure validation.",
      "Career: Symantec (Logging and Detection Engineering Lead) → Credit Karma (4 yrs 5 mos — Manager Security Engineering; SOC, SOAR automation, Splunk) → Okta (Director DCO Jan 2026–present).",
      "Promoted to Director, Defensive Cyber Operations in January 2026.",
    ],
    aiInitiatives: "Okta has moved decisively on AI governance in 2026. At Showcase 2026 (March), Okta announced the 'Blueprint for the Secure Agentic Enterprise' answering three critical governance questions: where are my agents, what can they connect to, and what can they do? Okta for AI Agents (GA April 30, 2026) provides: continuous discovery of known and unknown AI agents; registration as non-human identities with lifecycle management in Universal Directory; fine-grained access policies at runtime; and Universal Logout as an instant kill switch for rogue agents.\n\nIn late May 2026, Okta extended Okta for AI Agents to govern customer-deployed agents built on Amazon Bedrock AgentCore. Okta is simultaneously building out its internal data classification and governance program — actively discovering and inventorying sensitive data (PII, SPI, financial, IP, AI training data) across Google Workspace, Salesforce, Workday, NetSuite, and Snowflake. Per Okta's own research: 91% of organizations have AI agents in production; only 10% have a strategy for managing non-human identities.",
    worldRightNow: "$2.92B revenue. Recovering from 2023 support system breach. Board-level cybersecurity oversight strengthened. Post-2023 breach, data visibility is a board-level priority.",
    painPoints: [
      "Okta's identity graph contains the entitlement data that makes DSPM actionable — Bedrock tells you what the data is, Okta controls who touches it.",
      "Post-2023 breach, data visibility gaps are a board-level concern and classification is a live gap.",
      "AI agents as new identities multiplying the access surface as Okta for AI Agents scales — what data can those agents reach?",
      "Detection engineering background: evaluates tools on signal quality and noise reduction, not marketing claims.",
    ],
  },
  {
    name: "Marzi West",
    title: "Technology Compliance Strategy Lead",
    company: "Stripe",
    pronoun: "she",
    employees: "8,000",
    revenue: "$5.1B",
    li: "https://www.linkedin.com/in/marzi-west-cissp-pmp-cisa-6423362/",
    stack: { aws: true, snowflake: false, databricks: true, gcp: false },
    rel: false, mit: false, conn: true,
    ai: "8 months into role at Stripe, actively assessing security posture — prime window for new vendor relationships. $1.9T payment volume means AI data access classification is urgent.",
    whoTheyAre: [
      "12 years of deep Salesforce product security compliance expertise. New in role at Stripe — actively assessing security posture and building her programme. Event Ambassador, 37th America's Cup.",
      "Career: Salesforce (12 years, most recently Sr Director Product Security Compliance) → Stripe (Technology Compliance Strategy Lead, Oct 2025–present). 8 months into current role.",
      "Education: Alfred Lerner College of Business & Economics, University of Delaware (BS Finance and MIS) · UC Berkeley Executive Education (Technology Leadership). Certifications: CISSP, PMP, CISA.",
    ],
    aiInitiatives: "Stripe is rearchitecting its entire platform as economic infrastructure for AI. At Stripe Sessions 2026 (April 29, 288 product announcements): Stripe launched the Payments Foundation Model — an industry-first AI model for payments using self-supervised learning; expanded the Agentic Commerce Suite enabling AI agents to execute commerce transactions; introduced Link's agent wallet for AI-initiated payments; and unveiled Stripe MCP enabling AI agents to retrieve real-time subscription metrics. CEO Patrick Collison: in the near future AI agents will account for most transactions online.\n\nStripe's compliance posture is rigorous: PCI DSS Level 1 certified, SOC 2 Type II, and ISO 27001 as of March 2026. As of 2026, Stripe is strengthening KYC/AML and security controls as agentic commerce scales. SOX, GDPR, and CCPA all apply at $1.9T annual payment volume.",
    worldRightNow: "$159B valuation. $1.9T payment volume in 2025 for 5M businesses. $5.1B revenue. PCI DSS, SOX, GDPR all apply. As Marzi is 8 months into her role and actively assessing Stripe's security posture, she is in the prime window for new vendor relationships and governance tooling decisions.",
    painPoints: [
      "Stripe processes payment data for 5M businesses — knowing what AI systems can see is urgent at $1.9T volume.",
      "AI agents as economic actors creating new data access patterns that compliance frameworks have not yet classified.",
      "8 months into role — actively assessing gaps; prime window for new vendor relationships.",
      "PCI DSS compliance at Stripe's scale requires continuous, automated data classification to be maintainable.",
    ],
  },
  {
    name: "Marzena Fuller",
    title: "CISO",
    company: "Cognite",
    pronoun: "she",
    employees: "574",
    revenue: "$120.6M",
    li: "https://www.linkedin.com/in/marzenafuller/",
    stack: { aws: true, snowflake: false, databricks: false, gcp: true },
    rel: false, mit: false, conn: true,
    ai: "5 months into her CISO role, actively building the security program. Databricks background gives her a direct frame of reference for Bedrock's positioning.",
    whoTheyAre: [
      "Builds cybersecurity functions from the ground up at technically complex organizations. Writes publicly about AI security and LLMs — most recent article: 'Why Understanding Jailbroken LLMs Is the Innovation Edge Your Organization Needs.'",
      "Career: Databricks (Senior Director, Security) → Cisco → Warner Music Group (Cybersecurity Executive, Nov 2023–Feb 2026) → Cognite (CISO, Feb 2026–present).",
      "Education: Harvard University executive programme (2015–2018).",
      "5 months into role — actively building the CISO function and evaluating the security and governance tooling landscape. Prime vendor evaluation window.",
    ],
    aiInitiatives: "Cognite is the global leader in Industrial AI and has made data governance a first-class product capability. In Q1 2026, Cognite released precision governance controls within the Atlas AI agent workbench — replacing blanket role-based permissions with agent-level ownership assignment. The Cognite Industrial Knowledge Graph was enhanced for richer context in agent reasoning, organizing OT and IT data to reflect how industrial operations actually work.\n\nIn January 2026, Cognite partnered with Snowflake to scale industrial AI for oil and gas, explicitly supporting secure data governance and collaboration across internal teams and external partners. In May 2026, Cognite launched Cognite Flows — an AI-native industrial workflow platform — and was named a Front Runner in the LNS Research Solution Selection Matrix for Industrial AI Platforms. Atlas AI is built with enterprise-grade security, auditing, and compliance features; administrators define who can create or deploy agents, and high-impact tools require explicit confirmation to protect proprietary data.",
    worldRightNow: "$120.6M revenue, 574 employees. IDC MarketScape Leader for Industrial DataOps Platforms 2026. Exceeded $170M ARR in 2025.",
    painPoints: [
      "Industrial AI agents accessing OT data — physical infrastructure implications make governance uniquely high-stakes.",
      "Cognite's platform merges OT and IT data — classification challenge is more complex than standard enterprise cloud.",
      "5 months into role — actively building the CISO program and evaluating security and governance vendors.",
      "As Cognite scales agentic AI, who governs what each agent can see and act on across multi-site industrial operations?",
    ],
  },
  {
    name: "Steve Kim",
    title: "Director of Security",
    company: "Ethos",
    pronoun: "he",
    employees: "493",
    revenue: "$254.9M",
    li: "https://www.linkedin.com/in/hykim/",
    stack: { aws: true, snowflake: true, databricks: false, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "Ethos completed its Nasdaq IPO in Jan 2026 — SEC cybersecurity disclosure requirements apply for the first time. Governance documentation is now a legal requirement.",
    whoTheyAre: [
      "AI Security and Product Security specialist (top endorsed skills). Joined Ethos to embed security culture into the product. Also serves as Assistant Scout Master, Bay Area Council Boy Scouts of America.",
      "Career: eHealthInsurance → ClearSlide → Zuora → Coupang (Director, Product Security) → Ethos (Director of Security, May 2025–present).",
      "Certifications: CISSP, GSSP-JAVA. Education: MS, New Jersey Institute of Technology · BS, University of Bridgeport.",
    ],
    aiInitiatives: "Ethos completed its Nasdaq IPO on January 29–30, 2026 (ticker: LIFE, $19/share, $1.3B valuation, $211M raise) — triggering SEC cybersecurity disclosure obligations for the first time. Post-IPO, Ethos must publicly document its cybersecurity risk management program annually under Regulation S-K Item 106.\n\nEthos's underwriting engine evaluates up to 250,000 data points per application — prescription history, credit-based insurance scores, motor vehicle records — making sensitive data classification a foundational compliance requirement. In May 2026, Ethos launched its first ChatGPT-integrated life insurance product, creating new AI data access surfaces that require classification and governance. Ethos reported 65% Q4 growth and ended 2025 with more than 500,000 active policies.",
    worldRightNow: "$254.9M revenue, 493 employees. AWS + Snowflake. Post-IPO compliance requirements are new and urgent. $1.3B valuation at IPO.",
    painPoints: [
      "Newly public — SEC cybersecurity disclosure requirements apply for the first time; governance documentation is now a legal requirement.",
      "ChatGPT integration creates new AI data access surface that requires classification before it touches regulated insurance data.",
      "Small team, broad responsibility — needs tools that provide value without heavy overhead.",
      "Sensitive health and PII data at scale, now under heightened regulatory scrutiny post-IPO.",
    ],
  },
  {
    name: "Bill Young",
    title: "Head of Security",
    company: "Seismic",
    pronoun: "he",
    employees: "1,363",
    revenue: "$286.3M",
    li: "https://www.linkedin.com/in/billyoung4/",
    stack: { aws: true, snowflake: true, databricks: false, gcp: true },
    rel: false, mit: false, conn: false,
    ai: "Seismic-Highspot merger signed Feb 2026 — post-merger data consolidation creates a governance and tooling re-evaluation window across two previously competing platforms.",
    whoTheyAre: [
      "Security assessment, planning, design, implementation, and improvement practitioner. Naval Academy background — structured, disciplined, direct.",
      "Career: CompuCom (21 yrs — Consultant, Consulting Advisor, Principal Consultant) → Percolate Inc. (Head of Security) → Seismic (Jan 2021–present, 5 yrs 6 mos).",
      "Education: BS, United States Naval Academy (Judo Team, Karate Team). Certifications: CCNP Wireless (Cisco), Symantec Technical Specialist, and 5 others.",
      "⚠ LinkedIn as of June 10, 2026 shows Bill still active at Seismic. Confirm status at dinner.",
    ],
    aiInitiatives: "The Seismic-Highspot merger was signed February 12, 2026 — creating the category-defining platform in AI-powered revenue enablement under the Seismic brand, led by CEO Rob Tarkoff. The merger combines Seismic's deep enterprise governance and automation with Highspot's agentic GTM performance capabilities. Seismic had previously launched Aura AI (Winter 2026).\n\nPost-merger integration cycles typically divert engineering from innovation to reconciliation for 12–18 months — creating a governance and tooling re-evaluation window at the combined entity.",
    worldRightNow: "Seismic-Highspot merger signed February 12, 2026. Combined company operates as Seismic. AWS + Snowflake + GCP. $286.3M revenue.",
    painPoints: [
      "Post-merger data consolidation across two previously competing platforms surfaces DSPM and data governance gaps.",
      "M&A integration creates data sprawl across combined customer environments that security teams must govern.",
    ],
  },
  {
    name: "Maxim Hudaley",
    title: "CISO",
    company: "Complete Genomics Inc.",
    pronoun: "he",
    employees: null,
    revenue: null,
    li: "https://www.linkedin.com/in/maxim-hudaley/",
    stack: { aws: false, snowflake: false, databricks: false, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "Built Complete Genomics' first cybersecurity function from zero. Cross-border M&A (Swiss Rockets acquisition) creates new US↔Switzerland data governance complexity right now.",
    whoTheyAre: [
      "Built Complete Genomics' first cybersecurity function from zero — transforming an unprotected biotech into a security-capable organization protecting sensitive genomic and life sciences data.",
      "Active LinkedIn writer on AI security and LLM topics. CISSP certified. Top skills: Risk Management, Artificial Intelligence (AI).",
      "Career: Complete Genomics Inc. (CISO, Jun 2023–present). Prior roles not shown in visible LinkedIn.",
    ],
    aiInitiatives: "Complete Genomics (founded 2005, San Jose) is a U.S.-based life sciences company providing end-to-end DNA sequencing platforms, reagents, and software — its DNBSEQ technology has supported 10,900+ scientific publications. In April 2026, it announced that AI-trained variant calling models reduce genome analysis errors by up to 73% on DNBSEQ data versus industry-standard pipelines. At AGBT 2026 (February) it launched the DNBSEQ-T7+ high-throughput platform for population-scale genomics. These AI sequencing pipelines process human genomic data — among the most sensitive personal data in existence: a single individual's genome is permanently identifying, cannot be changed like a password, and has family-wide implications.\n\nOn February 23, 2026, Complete Genomics entered a definitive agreement to be acquired by Swiss Rockets AG (a Switzerland-based life sciences group focused on oncology and precision medicine), moving it out of its prior MGI/BGI ownership. The acquisition introduces cross-border data governance complexity (US ↔ Switzerland), supply chain diversification, and a new ownership structure — exactly the kind of M&A event where data governance gaps surface.",
    worldRightNow: "Founded 2005, San Jose. End-to-end DNA sequencing platforms supporting 10,900+ scientific publications. Acquisition by Swiss Rockets AG signed Feb 2026 (pending MGI shareholder approval). AI-driven variant calling and population-scale sequencing are the growth frontier.",
    painPoints: [
      "Governing AI access to genomic and life sciences data — the stakes of misclassification are uniquely severe and irreversible.",
      "Cross-border data governance complexity from the Swiss Rockets acquisition (US ↔ Switzerland data flows, new ownership structure).",
      "HIPAA / research-use data handling for genomic data intersecting with AI training and variant-calling pipelines.",
      "Built the security function from scratch — actively evaluating tools to mature the program through an ownership transition.",
    ],
  },
  {
    name: "Saran Makam",
    title: "VP Information Security and IT",
    company: "Observe.AI",
    pronoun: "he",
    employees: null,
    revenue: null,
    li: "https://www.linkedin.com/in/saran-makam-sec-arch/",
    stack: { aws: false, snowflake: false, databricks: false, gcp: false },
    rel: false, mit: false, conn: false,
    ai: "Launched Voice AI Agents security from day one at Observe.AI — VoiceAI agents process unstructured call recordings containing PII, payment, and health data that traditional DLP cannot classify.",
    whoTheyAre: [
      "Launched Voice AI Agents security and compliance at Observe.AI from day one — establishing HITRUST R2, PCI, and SOC2 from the ground up.",
      "Career: Goldman Sachs (Software Engineer, Bengaluru) → Envestnet/Yodlee (Senior Manager Application Security) → Envestnet Inc. (Director Product and Cloud Security) → Poshmark (Head of Security, Jan 2021–Mar 2025) → Observe.AI (VP Information Security and IT, Mar 2025–present).",
      "Uses risk-based approaches to build security programs that last.",
    ],
    aiInitiatives: "Observe.AI is a conversation intelligence and automation platform for contact centers (founded 2017, Redwood City; ~$214M raised). Its platform processes deeply sensitive data: contact center call recordings, transcripts, and customer interactions containing PII, payment card data, and health information. In December 2025, Observe.AI launched VoiceAI agents — autonomous voice AI built on in-house models plus OpenAI and Anthropic LLMs — to automate routine customer calls. In May 2026 it launched a Companion Agent for frontline teams.\n\nThe platform analyzes 100% of customer interactions, automatically detects and masks PII, and emphasizes a 'Trust, Security & Responsible AI' governance layer. Saran launched the security and compliance program for Voice AI Agents from day one, establishing HITRUST R2, PCI, and SOC2 — each requiring comprehensive evidence of data classification, access controls, and governance. The governance challenge is squarely the DSPM problem: AI agents processing unstructured audio and transcript data, with PII embedded in conversational content that traditional tools cannot classify.",
    worldRightNow: "Conversation intelligence and Voice AI platform for contact centers. Founded 2017, Redwood City. ~$214M raised. CEO Swapnil Jain. VoiceAI agents (Dec 2025) and Companion Agent (May 2026) live, built on OpenAI and Anthropic LLMs.",
    painPoints: [
      "Voice AI Agents processing unstructured conversational data containing PII, payment, and health data — classification is a live, unsolved problem.",
      "HITRUST R2 and PCI compliance demand rigorous evidence of data classification and access controls.",
      "AI agent access to customer conversation data creates exposure vectors traditional DLP cannot address.",
      "14 months into role at a fast-growing AI company — actively building out the governance and tooling stack.",
    ],
  },
];
